[package]
name = "blink"
version = "0.1.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]
edition = '2018'

[dependencies]
ruduino = "0.2"

[profile.release]
panic = "abort"
codegen-units = 1
# reduces size considerably
debug = false
lto = true
opt-level = "s"
